cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<int:product_id>/', views.update_cart, name='update_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('summary/', views.cart_summary, name='cart_summary'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('store.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('pre-order/', views.preorder, name='pre-order'),
    path('register/', views.register_user, name='register'),
    path('update_user/', views.update_user, name='upadate_user'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('Product/<int:pk>', views.product, name='product'),
    path('about/', views.about, name='about'),
]

store/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(user, auto_now=True)
    phone = models.CharField(max_length=20, blank=True)
    address1 = models.CharField(max_length=200, blank=True)
    address2 = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200, blank=True)
    state = models.CharField(max_length=200, blank=True)
    zipcode = models.CharField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    Category = models.ForeignKey(Category, on_delete=models.CASCADE, default='', blank=True, null=True)
    image = models.ImageField(upload_to='uploads/products')

    def __str__(self):
        return self.name

class CartManager(models.Manager):
    def get_or_create_cart(self, user):
        cart, created = self.get_or_create(user=user)
        return cart, created


class Oder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    Customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    adress = models.CharField(max_length=100, default='', blank=True)
    phone = models.CharField(max_length=20, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)
    
    def __str__(self):
        return self.product
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')
    # other fields as needed

    def __len__(self):
        return self.cartitem_set.aggregate(total_items=models.Sum('quantity'))['total_items'] or 0


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in cart {self.cart.id}"

store/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from forms import SignUpForm
from django import forms

def product(request,pk):
    product = Product.objects.get(id=pk)
    return  render(request, 'product.html', {'product':product})

def home(request): 
    products = Product.objects.all()
    return  render(request, 'home.html', {'products':products})


def shop(request):
    products = Product.objects.all()
    return  render(request, 'shop.html', {'products':products})


def preorder(request):
    return  render(request, 'pre-order.html', {})

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, ('You have logged in successfully'))
            return redirect('home')
        else:
            messages.success(request, ('The details you have entered are incorrect'))
            return redirect('login')
    else:  
     return  render(request, 'login.html', {})
     
def logout_user(request):
    logout(request)
    messages.success(request, ("You have logged out sucessfully"))
    return redirect('home')

def register_user(request):
	form = SignUpForm()
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			# first_name = form.cleaned_data['first_name']
			# second_name = form.cleaned_data['second_name']
			# email = form.cleaned_data['email']
			# Log in user
			user = authenticate(username=username, password=password)
			login(request,user)
			messages.success(request, ("You have successfully registered! Welcome!"))
			return redirect('home')
          	
	return render(request, "register.html", {'form':form})

def update_user(request):
     return render(request, "update_user.html") 


def slideshow(request):
    products = Product.objects.all()
    return  render(request, 'home.html', {'products':products})

def about(request):
    return  render(request, 'about.html', {})

store/templates/about.html

{% extends 'base.html' %}

{% block content %}
    
         <section class="layout contained">
        <div class="login">
          <div class="product-titles">Contact</div>
          <p>Email: <a href="mailto:mmashudu@hotmail.com">mmashudu@hotmail.com</a></p>
      <p>LinkedIn: <a href="https://www.linkedin.com/in/mashudu-malukwe-940630116/" target="_blank">linkedin.com/in/mashudu_malukwe</a> | GitHub: <a href="https://github.com/mashudu2021" target="_blank">https://github.com/mashudu2021</a></p>
      | website: <a href="https://mmashudu.pythonanywhere.com" target="_blank">mmashudu.pythonanywhere.com</a></p>
      <p>| Phone: 0814108036</p>
      <div class="line"></div>
      <div class="product-titles">Technical Proficiencies</div>
          <div class="product-description">
          
          <ul>
            <li>• Languages: Python </li>
            <li>• Libraries/Frameworks: Django, Matplotlib, Plotly, BeautifulSoup, Scrapy,</li>
            <li>• Database Systems: SQLite, SQL</li>
            <li>• Tools: Jupyter Notebook, Git, Github</li>
          </ul>
          </div>
          <div class="line"></div><div class="product-titles">Education</div>
          <div class="product-description">
          <p class="product-description">Programming for Everybody (Getting Started with Python)</p>
          <p >[University of Michigan]</p>
           </div>
           <div class="product-description">
            <p class="product-description">Django for Everybody Specialization</p>
            <p >[University of Michigan]</p>
             </div>
           <div class="line"></div>
          <p class="product-titles">Technical Skills</p>
          <div class="product-description">
          
          <ul>
            <li>• Programming language: Python HTML </li>
            <li>• Web Technologies: HTML, CSS, JavaScript</li>
            <li>• Web Scraping: BeautifulSoup, Scrapy</li>
            <li>• Data Formats: JSON, XML</li>
            <li>• Database Management: SQLite, SQL</li>
            <li>• Data Visualization: Matplotlib, Seaborn, Plotly</li>
            <li>• File Operations: Reading and writing files in various formats</li>
          </ul>
          </div>
          
        </div>
        <div class="login "> <div class="d-flex heade">
          <div class="user-pic"><img src="https://th.bing.com/th/id/OIP.kzBDyWRZbcY8gQcFpIFC1gAAAA?w=196&h=196&c=7&r=0&o=5&pid=1.7" height="100px" width="101px" style="border-radius: 50%;"></div>
          <div class="user-profile">
        <div class="product-title">Hello i am </div>
      <div class="name">Mashudu Malukwe</div>
      <div class="product-title">Frontend / Backend Developer; </div>
      
    </div>
      

    </div> <div class="line">
 
          <p class="product-titles">Professional Summary</p>
          <div class="product-description">
          <p >Skilled Python Developer with comprehensive experience in retrieving data from websites and APIs, understanding web protocols, and managing databases. Proficient in working with JSON and XML data formats, implementing web scraping techniques, and performing CRUD operations with SQLite and SQL. Adept at creating and analyzing data visualizations, and experienced with Django for developing web applications.</p>
          </div>
    </div>    
            <div class="product-titles">Projects</div>
    
            <p class="product-title">Web Crawler and Page Rank System</p>
            <div class="product-description">
          <p >• Developed a Python-based web crawler to extract and store web page data and links using SQLite.</p>
          <p >• Implemented a PageRank algorithm to calculate and refine page importance iteratively.</p>
          <p >• Designed and managed an SQLite database to handle page data and links efficiently.</p>
          <p >• Created a dynamic data visualization using D3.js to represent web page relationships and rankings in an interactive force-directed graph. </p>
          <p >• Utilized libraries such as BeautifulSoup and Requests for web scraping, and SQLite for data management.</p>
          <p >• Implemented error handling and data validation to ensure reliable data retrieval.</p>
          <p >• Demonstrated the project's functionality with a live demo, showing effective crawling, ranking, and visualization.</p>
          <p>Technologies: Python, SQLite, BeautifulSoup, Requests, D3.js, HTML, JavaScript</p>
              </div>
    
          
          <p class="product-title">Data Analysis and Visualization Dashboard</p>
          <div class="product-description">
          <p >• Created an interactive dashboard using Plotly and Dash to visualize complex datasets.</p>
          <p >• Analyzed data trends and patterns with Pandas, presenting findings through various charts and graphs.</p>
          <p >• JSON and XML data, storing results in SQLite databases for further analysis.</p>
          <p >• Enabled real-time data updates and user interactions for enhanced data insights.</p>
          
          </div>
          <p class="product-title">Django Web Application</p>
          <div class="product-description">
          <p >• Developed a web application using Django, featuring user authentication, data management, and interactive components.</p>
          <p >• Integrated SQLite database to manage user data, implemented CRUD functionalities, and ensured seamless data operations. </p>
          <p >• Designed data visualizations to display real-time data trends and user interactions on the web interface. </p>
    </div>
          <p class="product-title">Database Management System Integration with Tkinter</p>
          <div class="product-description">
          <p >• Designed and implemented a SQLite database schema for managing user information and application data.</p>
          <p >• Utilized SQL queries to perform CRUD operations and ensure data consistency.</p>
          <p >• Developed scripts to automate database maintenance tasks and data integrity checks.</p>
    </div>
    
    <div class="line"></div>    
    <div class="product-titles">Certifications</div>
    <div class="product-description">
    <p >• Python Data Structures – [University of Michigan], [2021]</p>
    <p >• Using Databases with Python – [University of Michigan], [2021]</p>
    <p >• Using Python to Access Web Data – [University of Michigan], [2021]</p>
    <p >• Capstone: Retrieving, Processing, and Visualizing Data with Python – [University of Michigan], [2021]</p>
    <p >• Web Application Technologies and Django – [University of Michigan], [2021]</p>
    <p >• Building Web Applications in Django – [University of Michigan], [2021]</p>
    <p >• Django Features and Libraries – [University of Michigan], [2022]</p>
    </div>
    

 
    </div>
      </section>

{% endblock %}

store/templates/base.html
<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Drip Footware</title>
<meta name="description" content="drip shoe store">
<meta name="author" content="Mashudu  Malukwe">
<meta name="copyright" content="Mashudu malukwe">
<meta name="robots" content="index, follow">
<meta name="csrf-token" content="{% csrf_token %}">

{% load static %}
<html>
    <head> 
    </head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

      </script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
    
<body style="margin: 0;background: #ffffff;">
  <div class=" desktop-1" data-id="1:2" data-page="desktop-1" data-screens="desktop-4,desktop-3,desktop-2,desktop-1" style="opacity: 1;">

    {% if messages %}
        {% for message in messages %}
        <div class="alert">
          <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% include 'navbar.html'%}
  {% block content %}
  {% endblock %}
 </div>
  </body>  
  <footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6>About</h6>
          <p class="text-justify"><i>INNOVATION & CREATIVITY</i> Drip is a brand dedicated to working with customers to design the future.</p>
        </div>
  
        <div class="col-xs-6 col-md-3">
          <h6>Menu</h6>
          <ul class="footer-links">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'shop' %}">Shop</a></li>
            <li><a href="{% url 'pre-order' %}">Pre-order</a></li>
            <li><a href="tracker">Tracker</a></li>
            <li><a href="about-us">About Us</a></li>
          </ul>
        </div>
  
        <div class="col-xs-6 col-md-3">
          <h6>Payment Accepted</h6>
          <ul class="footer-links">
            <li><img src="/static/images/card.png" height="52" width="52" alt="Card" /></li>
            <li><img src="/static/images/visa.png" height="50" width="60" alt="Visa" /></li>
            <li><img src="/static/images/paypal.png" height="50" width="70" alt="PayPal" /></li>
            <li><img src="/static/images/shopping.png" height="50" width="70" alt="Shopping" /></li>
          </ul>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">Copyright &copy; 2024 All Rights Reserved by <a href="#">Drip</a>.</p>
        </div>
  
        <div class="col-md-4 col-sm-6 col-xs-12">
          <ul class="social-icons">
            <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
          </ul>
        </div>
      </div>
    </div>
  </footer>
</html>

store/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="main">
    <div class="rectangle-1-C61RwL" onclick="Lib.autoanim_redirect('desktop-4,desktop-1%23desktop-3,,ease-in,255.5234432220459;desktop-3,desktop-1%23desktop-2,,ease-in,255.5234432220459;desktop-2,desktop-1%23desktop-1,,ease-in,255.5234432220459', event)" onmouseover="" data-id="56:77"></div>
   
    <div class="frame-1-C61RwL" data-id="56:63">
      <div class="group-1-WzCX2w" data-id="56:64">
        <div class="logo-2-iBmTg4" data-id="56:65"></div>
        <div class="ellipse-1-iBmTg4" data-id="56:66"></div>
      </div>
      <h1 class="likwidz-WzCX2w" data-id="56:67">LIKWIDZ</h1>
      <div class="rectangle-2-C61RwL" onclick="Lib.autoanim_redirect('desktop-3,desktop-1%23desktop-4,,ease-in,255.5234432220459;desktop-2,desktop-1%23desktop-3,,ease-in,255.5234432220459;desktop-1,desktop-1%23desktop-2,,ease-in,255.5234432220459', event)" onmouseover="" data-id="55:53"></div>
      <div class="arrow-1-C61RwL" data-id="55:54"></div>
      
    
          
<div id="slider">
  <a href="#" class="control_next">></a>
  <a href="#" class="control_prev"><</a>
  
  <ul>
    {% for product in products reversed %}
            <li>
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="likwidz123456-1-zUix{{ forloop.counter }}" data-id="56:85">
            </li>
        {% endfor %}
  </ul>  
</div> 

      <div class="slider_option">
        <input type="checkbox" id="checkbox">
        <label for="checkbox">Autoplay Slider</label>
      </div> 
      </div>
      
<div class="contained">
          <h1 class="hd aligment">New arrival</h1>
          <div class="container inline">
          <div class="parent-container">
            {% for product in products reversed  %}
          <div class="item inline-item">
            <div class="product-image">
              <a href="{% url 'product' product.id %}"><img src="{{ product.image.url }}" alt="Product Image"></a>
            </div>
            <div class="product-details">
              <h2 class="title">{{ product.name}}</h2>
              <p class="price">R{{ product.price}}</p>
              <div class="buttons">
                <button  class="add-to-cart"  data-product-url="{% url 'product' product.id %}">View Product</button>
              </div>
            </div>
      
          </div>
          {% endfor %} 
          </div>
          </div>
</div> 
 
<div class="contained desktop-1">

<div class="header">Introducing Claws</div>
<div class="child">
      <div class="panels">
        
        <a class="panel">
          <div class="panel__content"><span class="claw">JAW CLAWS – ORANGE</span></div>
        </a>
        <a class="panel">
            <div class="panel__content"><span class="claw">BABY CLAWS – BLUE</span></div>
          </a>
          <a class="panel">
            <div class="panel__content"><span class="claw">PANTHER CLAWS – BLACK</span></div>
          </a>
          <a class="panel">
            <div class="panel__content"><span class="claw">TALON CLAWS – RED</span></div>
          </a>
          <a class="panel">
            <div class="panel__content"><span class="claw">TIGER CLAWS – YELLOW</span></div>
          </a>
          <a class="panel">
            <div class="panel__content"><span class="claw">EAGLE CLAWS – BEIGE</span></div>
          </a>
      </div>
      </div>
    </div>
      <div class="contained">
      <div class="panual1">
        
      <p class="product-descriptions"> <div class="hd">Drip Claws</div>
      Drip is about to drop claws a light weight breathable mesh sneakers, designed with an outer sole to grip the hardness of the ACTIVE functionality and beautiful lifestyle transition.
      The core of the sneaker is functionality.
      Designed to be lightweight and breathable to offer a long day wear and for lifestyle usage.
      This is our 1st step into our 1st step into our journey of Active/Lifestyle products, currently known as Athleisure.
      It's tome to be Cool and Active.</p>    
      </div>
</div>
    </div>

    <div class=" contained slid ">
      <div class="slide-track">
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0004_ROF_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0003_SOLEMATE_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0001_LIKWIDZ_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0007_bundle.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0007_claws.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0004_ROF_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0003_SOLEMATE_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0001_LIKWIDZ_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0007_bundle.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0007_claws.png" height="100" width="250" alt="" />
        </div><div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0004_ROF_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0003_SOLEMATE_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0001_LIKWIDZ_logo.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0007_bundle.png" height="100" width="250" alt="" />
        </div>
        <div class="slide">
          <img src="/static/images/branding/Drip_Brands_b_0007_claws.png" height="100" width="250" alt="" />
        </div>
      </div>
    </div>
  
<script >
  
  jQuery(document).ready(function ($) {
    
    $('#checkbox').change(function(){
      setInterval(function () {
          moveRight();
      }, 3000);
    });
    
      var slideCount = $('#slider ul li').length;
      var slideWidth = $('#slider ul li').width();
      var slideHeight = $('#slider ul li').height();
      var sliderUlWidth = slideCount * slideWidth;
      
      $('#slider').css({ width: slideWidth, height: slideHeight });
      
      $('#slider ul').css({ width: sliderUlWidth, marginLeft: - slideWidth });
      
      $('#slider ul li:last-child').prependTo('#slider ul');
  
      function moveLeft() {
          $('#slider ul').animate({
              left: + slideWidth
          }, 200, function () {
              $('#slider ul li:last-child').prependTo('#slider ul');
              $('#slider ul').css('left', '');
          });
      };
  
      function moveRight() {
          $('#slider ul').animate({
              left: - slideWidth
          }, 200, function () {
              $('#slider ul li:first-child').appendTo('#slider ul');
              $('#slider ul').css('left', '');
          });
      };
  
      $('a.control_prev').click(function () {
          moveLeft();
      });
  
      $('a.control_next').click(function () {
          moveRight();
      });
  
  });
   </script>
{% endblock %}

store/templates/login.html
{% extends 'base.html' %}

{% block content %}
    

    <section>

      <hgroup>
          <div class="h2s">Welcome back!</div>
        <p>Please enter your details to sign into your account</p>
      </hgroup>
    
      <form method = "POST" action="{% url 'login' %}" class = "login">
        {% csrf_token %}
          <div class="group log-input">
            <input type="text" id = "username" name = "username" placeholder = "username">
          </div>
    
          <div class="group log-input">
              <input type="password" id = "password" name = "password"  placeholder = "Password">
          </div>
          <div class="buttons">
            <button class="add-to-cart">Sign in</button>
          </div>
          <p class="message">Not registered? <a href="{% url 'register' %}">Create an account</a></p>
          
      </form>
    
      
    
    </section>
    </div>
{% endblock %}
      
    

store/templates/navbar.html
<section class="layout">
    <div class="search-1-1-C61RwL" data-id="56:68"></div>
{% if user.is_authenticated %}    
    <a href="{% url 'cart:cart_summary' %}" ><div class="shopping-cart-1-1-C61RwL" data-id="56:69"><span class="cart__count" id="cart-badge">{{ cart|length }}</span>
    </div></a>
{% else %} 
<a href="{% url 'login' %}" ><div class="shopping-cart-1-1-C61RwL" data-id="56:69">
</div></a>    
{% endif %}
{% if user.is_authenticated %}    
    <a class="logout" href="{% url 'logout' %}">log out |</a>
    <div class="user-1-C61R" data-id="56:70"></div>  
{% else %} 
    <a href="{% url 'login' %}">
    <div class="user-1-C61RwL" data-id="56:70"></div></a>

{% endif %}
    <a href="{% url 'home' %}"><div class="logo-1-C61RwL" data-id="56:71"></div></a>
    <div class="home-C61RwL" data-id="56:72" ><a href="{% url 'home' %}">Home</a></div>
    <div class="shop-C61RwL" data-id="56:73" ><a href="{% url 'shop' %}">Shop</a></div>
    <div class="pre-order-C61RwL" data-id="56:74"><a href="{% url 'pre-order' %}">pre-order</a></div>
{% if user.is_authenticated %}   
    <div class="tracker-C61RwL" data-id="56:75">tracker</div>
{% else %} 
<a href="{% url 'login' %}" ><div class="tracker-C61RwL" data-id="56:75">tracker</div></a>
{% endif %}
    <a href="{% url 'about' %}" ><div class="about-us-C61RwL" data-id="56:76">about me</div></a>
</section>

store/templates/pre-order.html
{% extends 'base.html' %}

{% block content %}
<div class="client">
<div class='sprite splash'></div>
</div>
{% endblock %}
      

store/templates/product.html
{% extends 'base.html' %}

{% block content %}
<div class="contain">
    <div class="product-cards">
        <div class="product-images">
            <img src="{{ product.image.url }}" alt="Product Image">
        </div>
        <div class="product-detail">
            <h2 class="product-titles">{{ product.name }}</h2>
            <div class="stock">
                {% if product.inventory > 10 %}
                    <div>In-Stock</div>
                {% elif product.inventory > 0 %}
                    <div><font color="red">Low Stock</font></div>
                {% else %}
                    <div><font color="red">Out-of-Stock</font></div>
                {% endif %}
            </div>
            <p class="product-prices">R{{ product.price }}</p>
            <form id="add_to_cart_form" method="post" action="{% url 'cart:add_to_cart' product_id=product.id %}">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <div class="custom-select">
                    <select name="size">
                        <option value="0">Select size</option>
                        <option value="3">Size 3</option>
                        <option value="4">Size 4</option>
                        <option value="5">Size 5</option>
                        <option value="6">Size 6</option>
                        <option value="7">Size 7</option>
                        <option value="8">Size 8</option>
                        <option value="9">Size 9</option>
                        <option value="10">Size 10</option>
                        <option value="11">Size 11</option>
                        <option value="12">Size 12</option>
                    </select>
                </div>
                <div id="button-elements">
                    <button class="add-to-cart1" type="submit">Add to Cart</button>
                    <div id="favorite">♥ Favorite</div>
                </div>
            </form>
            <p class="product-descriptions">
                The Drip Liwkidz are the first sneakers that we dropped; they are the legends behind the Drip brand. We imagined what would the Likwidz of the future look like, we then conceptualized and came up with the “Likwidz 23’. We designed the sneaker to offer a feeling of a massage on your feet. The outer sole has our heritage logo monogram and an octopus grid design. The sole can take on tough terrain and still offer much comfort from the EVA midsole.
            </p>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#add_to_cart_form').on('submit', function(event) {
        event.preventDefault(); 
        
        var form = $(this);
        var product_id = form.find('input[name="product_id"]').val(); 
        var size = form.find('select[name="size"]').val(); 
        var csrf_token = form.find('input[name="csrfmiddlewaretoken"]').val(); 
        
        var addToCartUrl = "/cart/add/" + product_id + "/";

        $.ajax({
            type: 'POST',
            url: addToCartUrl, 
            data: {
                'size': size,
                'csrfmiddlewaretoken': csrf_token,
                'quantity': 1 
            },
            dataType: 'json',
            success: function(response) {
                if (response.message) {
                    alert(response.message); 

                    
                    $('#cart_count').text(response.cart_count); 
                    $('#cart_total').text(response.cart_total); 

                    window.location.reload(); 
                } else {
                    alert('Error: ' + response.message); 
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.error('AJAX Error:', textStatus, errorThrown); 
            }
        });
    });
});
</script>
{% endblock %}